### ISSUE TITLE
Fixed link to Docker image

### ISSUE THREAD

**Issue by namandixit** [hamsterbase/hamsterbase#14]
Will it be possible to have a fixed link to the Docker image on Dockerhub (for example, something like `hamsterbase/hamsterbase:stable`) that automatically points to the latest stable version? Currently, the instructions say to use `hamsterbase/hamsterbase:0.4.2-stable`, but this will require manually checking whether a new update has been released or not.

**Comment by CaryTrivett** [comment]
The latest beta and stable versions can be downloaded via `hamsterbase/hamsterbase:beta` and `hamsterbase/hamsterbase:stable` in the future.
