### ISSUE TITLE
Deleting pages

### ISSUE THREAD

**Issue by namandixit** [hamsterbase/hamsterbase#15]
Is is possible to delete webpages saved in Hamsterbase? If yes, please document how to do this, since it is not obvious from the UI. If not, would it be possible to add this feature?

**Comment by DiamondYuan** [comment]
<img width="1210" alt="image" src="https://user-images.githubusercontent.com/9692408/202893402-ae554139-b481-4a6d-b2a8-9d4ddb6743bd.png">

hamsterbase support delete webpage.

**Comment by CaryTrivett** [comment]
<img width="1210" alt="image" src="https://user-images.githubusercontent.com/90044465/202893448-a2030310-3138-41df-8109-be9d17540e16.png">

delete button is on the right sidebar
