### ISSUE TITLE
RSS不能正常工作

### ISSUE THREAD

**Issue by glfruit** [hamsterbase/hamsterbase#18]
在视图页面点击RSS按钮，弹出新的页面，显示一段JavaScript代码而没有执行：

`(function agent() { let unlock = false document.addEventListener('allow_copy', (event) => { unlock = event.detail.unlock }) const copyEvents = [ 'copy', 'cut', 'contextmenu', 'selectstart', 'mousedown', 'mouseup', 'mousemove', 'keydown', 'keypress', 'keyup', ] const rejectOtherHandlers = (e) => { if (unlock) { e.stopPropagation() if (e.stopImmediatePropagation) e.stopImmediatePropagation() } } copyEvents.forEach((evt) => { document.documentElement.addEventListener(evt, rejectOtherHandlers, { capture: true, }) }) })() 收藏 How to build systems to achieve your personal goals | The Startup https://medium.com/swlh/dont-just-set-goals-build-systems-8158ac541df`

**Comment by CaryTrivett** [comment]
这个看上去是第三方插件导致的。 在浏览器里访问 rss 地址试试看？

**Comment by CaryTrivett** [comment]
我想关闭了，有更新可以重新打开。

**Comment by glfruit** [comment]
测试了一下，在Google Chrome里面打开隐私模式可以返回XML格式的内容，但是在Safari里面打开隐私模式还是一样的问题，直接把地址http://10.0.0.102:13001/feeds/views/36a42b51-8d17-480a-9aab-7310c4bd05cb/webpages?limit=100粘贴进地址栏回车还是同样的问题
