### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by holoword** [hamsterbase/hamsterbase#2]
1. 资料图栏增加一个 全部 选项
     现在只有未读，搜索选项，确实比较简洁，但是刚开始用的时候，点击未读以后保存的网页便消失，也无法在搜索种找到，用户第一次使用以及后续也会非常疑惑于我刚保存的东西去哪了。直到视图中建立相应选项才可见保存的所有网页。
2. 未读中栏目翻动以后才取消未读，而非点击后便失去未读属性。

**Comment by CaryTrivett** [comment]
目前只有滚动后才会把页面标记为已读。

可以通过 R 这个快捷键切换是否已读。
