### ISSUE TITLE
使用 docker 部署，并使用 nginx 代理后，wss 请求失败，页面空白

### ISSUE THREAD

**Issue by haydenull** [hamsterbase/hamsterbase#22]
开发者你好：
  这个软件用来保存网页快照非常舒服。

  我这边使用 docker 部署到 vps 后，再使用 nginx 代理，目的是使用自己的域名。

  但是目前使用 vps ip + 端口号访问正常，如果使用域名访问，就会出现空白页，看了下控制台，有个 wss 请求报错了，但我不知道我应该如何配 wss 代理。

  我尝试过这么配：

```nginx
# hamsterbase.haydenhayden.com
server {
  listen 80;

  server_name hamsterbase.haydenhayden.com;

  rewrite ^(.*) https://$server_name$1 permanent;

  location / {
    proxy_pass http://127.0.0.1:5260;
    root html;
    index index.html index.htm;
  }
}
server {
  listen       443 ssl http2;
  server_name  hamsterbase.haydenhayden.com;
  ssl_certificate         xxx.pem;
  ssl_certificate_key     xxx.key;
  location / {
    proxy_pass http://127.0.0.1:5260;
    root html;
    index index.html;
  }
  location /private/ws/ipc {
    proxy_pass http://127.0.0.1:5260;
  }
}
```
但是还是不行。

  这个是我部署的网页 https://hamsterbase.haydenhayden.com

  我对后端不是很了解，希望这不是个傻瓜问题。

  感谢开发者的付出。

<img width="560" alt="image" src="https://user-images.githubusercontent.com/17695989/219940825-9cb3918f-7487-4f71-8060-9b4eb9a90f2b.png">

**Comment by CaryTrivett** [comment]
不好意思，我也不太清楚怎么反向代理。 只能提供一下 hamsterbae 目前提供的 API 路径

/public/api   API server 使用的 API
/protected/api  点对点同步使用的 API
/private/api 网页版使用的 API
/external/api 基于 public api 拓展的 API。 如 singilegile
/private/ws/ipc 前后端通信使用的接口

**Comment by haydenull** [comment]
感谢帮助，问题解决了，也加上了密码。不过加上密码后 客户端使用token远程访问似乎连不上了，不过不影响，网页端好使
