### ISSUE TITLE
能把对应的网页截图高亮批注也同步过来吗？

### ISSUE THREAD

**Issue by mozhux** [hamsterbase/hamsterbase#24]
如题，目前只是同步了高亮的内容，能把整个页面截图形式过来吗？

**Comment by CaryTrivett** [comment]
之后会有阅读模式。 等阅读模式开发完以后，可以考虑同步内容过来。

**Comment by CaryTrivett** [comment]
感谢反馈，中文讨论可以发到 [兔小巢](https://support.qq.com/product/594778)

此 issue 已迁移 https://support.qq.com/products/594778/post/168873042119282419/
