### ISSUE TITLE
能加上用户验证吗？

### ISSUE THREAD

**Issue by Kaiyuan** [hamsterbase/hamsterbase#25]
现在 NAS 上建了一个服务，但是直接就能访问，能不能加上用户验证功能，这样我就能在外网访问了。

**Comment by CaryTrivett** [comment]
启动时加上 password 参数就行

**Comment by sanfang0766** [comment]
我现在是外网用Http Auth。如果是这样，浏览器应用是不是就不能直接外网用了？
自己电脑是可以 ZeroTier，但是工作电脑就不一样。

**Comment by CaryTrivett** [comment]
0.8 会发布 webdav 同步，支持用 webdav 储存、同步数据。
