### ISSUE TITLE
Can't import this page

### ISSUE THREAD

**Issue by nhan000** [hamsterbase/hamsterbase#26]
Saved from https://www.nytimes.com/2023/06/23/travel/shikoku-pilgrimage-japan.html using Zotero (I'm quite sure Zotero use SingleFile to create webpage snapshot).

HTML file https://drive.google.com/file/d/14qWkWDsUVim4BTKkOyG7DVMzQuhdmm49/view?usp=sharing

**Comment by CaryTrivett** [comment]
<img width="1170" alt="image" src="https://github.com/hamsterbase/hamsterbase/assets/90044465/9fc3f902-ae9d-4685-ac4f-974c48b3c5d6">

Sorry, I have no way to reproduce it on my computer. I can successfully import your html from google drive.

May I ask what version you are using and what software you are using to import it?

If the html format doesn't work, try mhtml.

**Comment by nhan000** [comment]
Okay so I tested this again. The bug is that after I import the file it doesn't show up. When I close and reopen HamsterBase it then appeared. Windows 11, Hamsterbase 0.7.2.
![image](https://github.com/hamsterbase/hamsterbase/assets/85216095/82b7c2bf-bec8-4d49-a665-3661ee39b31b)

- - -

Since you're here, could you check this bug as well?

What it should look like (opened in Edge Stable, updated)
![image](https://github.com/hamsterbase/hamsterbase/assets/85216095/19d92744-65b1-4d90-a6fe-9826aa6f2149)

In HamsterBase, the bottom part of page is brought to the front, creating the messy overlapping part.

![image](https://github.com/hamsterbase/hamsterbase/assets/85216095/88b79231-7c32-463e-a392-45ff435038d0)

**Comment by CaryTrivett** [comment]
I reproduced the problem, and I'm still seeing how to fix it.

**Comment by CaryTrivett** [comment]
fix in 0.7.3
