### ISSUE TITLE
chrome插件报错,无法连接 win server/desktop版

### ISSUE THREAD

**Issue by leeyaunlong** [hamsterbase/hamsterbase#27]
chrome插件报错,无法连接 win server/desktop版,
报错如下:
chrome.action.setBadgeTextColor is not a function

![image](https://github.com/hamsterbase/hamsterbase/assets/19405648/2b43925c-4469-4212-a4e3-073ff070c617)

![image](https://github.com/hamsterbase/hamsterbase/assets/19405648/1ef9c198-21bf-41f4-ab4f-c9fd53335ac2)

**Comment by CaryTrivett** [comment]
用的是什么浏览器

**Comment by leeyaunlong** [comment]
(Chromium 102.0.5005.167)

**Comment by leeyaunlong** [comment]
> 用的是什么浏览器
 (Chromium 102.0.5005.167)

**Comment by CaryTrivett** [comment]
> > 用的是什么浏览器
> > (Chromium 102.0.5005.167)

https://github.com/w3c/webextensions/issues/216

我大概懂了，这个 API 在  Chrome 110 可用

**Comment by CaryTrivett** [comment]
已经修复，https://github.com/hamsterbase/hamsterbase-highlighter/commit/ae0e7de4b4b5b6eacce6fe38b69db18578a25cfe

晚上提交审核

**Comment by CaryTrivett** [comment]
https://github.com/hamsterbase/hamsterbase-highlighter/releases/tag/v1.3.2
