### ISSUE TITLE
sync to logseq 插件 无法更新多次高亮的笔记

### ISSUE THREAD

**Issue by leeyaunlong** [hamsterbase/hamsterbase#28]
sync to logseq 插件 无法更新多次高亮的笔记
每篇文章只会插入一次.

1. 假设有文章 A100. 我先加了高亮 Line1.
2. 在logseq 中执行sync操作, A100 的 Line1 会被加入.
3. 再去hamster 的A100 加一条高亮 Line2 , 另外一个A200的文章加条高亮 Line3
4. 然后再logseq执行sync, A200的高亮会同步过来, 但是A100没有变化.

**Comment by leeyaunlong** [comment]
logseq v0.98版, hamster 0.7.2

**Comment by CaryTrivett** [comment]
中文反馈后续统一在兔小巢，我在兔小巢建立了对应 反馈，这里先关了

https://support.qq.com/embed/phone/594778/post/168870693920757179/

**Comment by CaryTrivett** [comment]
新版本已修复
