### ISSUE TITLE
建议实现几个个功能点,就闭环了.

### ISSUE THREAD

**Issue by leeyaunlong** [hamsterbase/hamsterbase#29]
1. 后台存储的数据结构, 如何快速备份简单的目录+网页的归档. 
2. chrome保存/批注过的网址,能不能直接跳到hamster里面对应的节点去. 每次要搜索.
3. 随时可以右键导出文章或者批注成网页
4. 全文检索还比较弱,如果可能,最好提高一下精度.

**Comment by CaryTrivett** [comment]
感谢反馈，中文讨论可以发到 [兔小巢](https://support.qq.com/product/594778)

此 issue 已迁移 https://support.qq.com/products/594778/post/168873033816225716/
