### ISSUE TITLE
v2ex 帖子页面不能保存

### ISSUE THREAD

**Issue by holoword** [hamsterbase/hamsterbase#3]
![屏幕截图 2022-10-15 174102](https://user-images.githubusercontent.com/22163224/195979796-f7e91754-b556-4d71-8cdf-9781dffa6d86.png)
会报webdav 500 错误，但是v2ex的首页却不会报错。
同时，替换webdav以后也能够成功保存

**Comment by CaryTrivett** [comment]
下个版本会解决这个问题

**Comment by CaryTrivett** [comment]
fix in 0.5.0-beta
