### ISSUE TITLE
Webdev API endpoint not working with Singlefile

### ISSUE THREAD

**Issue by errorsandwarnings** [hamsterbase/hamsterbase#32]
Hi,

I am on chrome  + macos. Hamsterbase is running locally. I have configured hamsterbase to accept API endpoint and SingleFile sends the file and also think it was successful. However, it does not go through. Hamsterbase does not show any new imported files and neither does reload or force reloading shows any. Can you please explain if this is a bug ?

HamsterBase Version : 0.8.1

Thank You

**Comment by CaryTrivett** [comment]
url shoud end with `/external/api/singlefile`

**Comment by CaryTrivett** [comment]
1. Are you sure the url is correct?
2. After clicking on copy entrypoint, is it accessible in the browser?
3. f it’s not working, maybe try switching to another port

**Comment by silversheaf** [comment]
This problem is still happening, and on the [Singlefile forums others are having this problem too](https://github.com/gildas-lormeau/SingleFile/issues/1316) and suggesting that HamsterBase is the issue.
