### ISSUE TITLE
自动解析 inbox 里的大文件失败

### ISSUE THREAD

**Issue by virlaser** [hamsterbase/hamsterbase#34]
* 版本：0.8.1
* 构建方式：使用源码自行构建Docker镜像，构建脚本见下方代码。（项目提供的Docker镜像太老，NAS无法正常使用）
* 问题：给容器限制3G内存占用，上传到inbox文件夹的html文件（37.7MB大小，SingleFile插件导出）无法自动解析，会被移动到ignored文件夹，同时main.js所在路径会产生一个core文件。在页面上手动上传此文件可以成功。
* 希望优化的地方：1. 减少解析文件内存占用。解析上述文件时峰值内存占用可达1.2G，对NAS不友好。2. 修复大文件的自动解析问题。
* 其他问题：希望添加更强的搜索筛选功能，例如可以用过滤器控制搜索的范围，或者使搜索条件仅对某个视图生效。

祝愿产品越来越好~

```Dockerfile
FROM ubuntu:20.04
WORKDIR /app
COPY . /app
RUN apt update &&  \
    apt install -y curl &&  \
    curl -sL https://deb.nodesource.com/setup_14.x | bash - &&  \
    apt install -y nodejs && \
    npm install
VOLUME ["/root/hamsterbase"]
EXPOSE 3001
ENTRYPOINT ["node", "main.js"]
```

**Comment by CaryTrivett** [comment]
未来搜索可以做过滤功能。 视图也会加过滤功能。

不过两者应该不会二合一。
