### ISSUE TITLE
使用docker部署，做了一些简单的测试。

### ISSUE THREAD

**Issue by yyysuo** [hamsterbase/hamsterbase#35]
1：docker版本创建时不支持 --port 3001 --password 123，去除这2个选项后创建成功。
docker run -d --port 3001 --password 123 --restart=unless-stopped --mount type=tmpfs,destination=/tmp -p 888:3001/tcp -v /mnt/sda3/hamsterbase:/app/data --name hamsterbase  hamsterbase/hamsterbase:latest

2：chrome插件在d板点击扩展图标提示：
缃戦〉瑙ｆ瀽澶辫触 鍙嶉鍦板潃锛� https://hamsterbase.com/zh/docs/support.html
点击https://developer.mozilla.org/zh-CN/docs/Learn会成功，设置成自动开启后，d板可标注。

3：singfile设置完api之后，保存网页提示完成，但是并没有显示在hamsterbase当中，访问http://10.10.10.200:888/external/api/singlefile 会自动跳转到未读界面
4：希望支持微信读书，微信读书内容通过singlefile下载到本地，再上传到hamsterbase，显示是图片，无法做标注。
5：mobile界面，可以显示保存的网页列表，但是提示网页解析失败。

**Comment by CaryTrivett** [comment]
1.  password 需要到 hamsterbase/hamsterbase:latest 后面
2. 放到反馈社区了 https://support.qq.com/products/594778/post/169373421964049951/
3. 无法复现，可以找我私聊解决。
4.  放到反馈社区 https://support.qq.com/products/594778/post/169373439259043158/
5.  部分网页需要适配
