### ISSUE TITLE
Article reader mode

### ISSUE THREAD

**Issue by empedia** [hamsterbase/hamsterbase#36]
Hi,

I like the fact that HamsterBase works with SingleFile which provides the highest fidelity with an original web page that I have found so far, however, I would really like to be able to just view an article standalone without seeing any of the sidebars etc. - this would be ideal for integrating into Excalidraw's frame mode inside Obsidian.

I noticed that the article page is in an iframe but when I tried to just load the src of the iframe then the whole page was regenerated.

**Comment by CaryTrivett** [comment]
you can try  `/mobile`

**Comment by matthew-dexter-trimble** [comment]
Can you give me a full  example url - if I try

https://demo.hamsterbase.com/webpages/61eff366fe23b74cef95ce22b695c6c3f0af82bb243a9a335d76e47d8f301ad2/mobile I just get the same as the non-mobile page.

Likewise if I try 

https://demo.hamsterbase.com/mobile/61eff366fe23b74cef95ce22b695c6c3f0af82bb243a9a335d76e47d8f301ad2

I get redirected to the webpages_unread page.

In Chrome if I switch to using a response view I just get the same as the main view but squashed horizontally.

**Comment by CaryTrivett** [comment]
> Can you give me a full example url - if I try
> 
> https://demo.hamsterbase.com/webpages/61eff366fe23b74cef95ce22b695c6c3f0af82bb243a9a335d76e47d8f301ad2/mobile I just get the same as the non-mobile page.
> 
> Likewise if I try
> 
> https://demo.hamsterbase.com/mobile/61eff366fe23b74cef95ce22b695c6c3f0af82bb243a9a335d76e47d8f301ad2
> 
> I get redirected to the webpages_unread page.
> 
> In Chrome if I switch to using a response view I just get the same as the main view but squashed horizontally.

Need to upgrade to Hamsterbase version 0.9.1. I forgot to upgrade before.

https://demo.hamsterbase.com/mobile/webpages/webpages_all

**Comment by CaryTrivett** [comment]
Your request is in the plan. However, the current main goal is to develop iOS and Android, so this need might be realized later.

**Comment by matthew-dexter-trimble** [comment]
OK, fair enough. Doesn't seem like to complex a request though - maybe you could consider implementing it sooner. 

However it is in the plan, I will close this issue now.

**Comment by empedia** [comment]
Sorry just realised I was logged in with the wrong account.

**Comment by CaryTrivett** [comment]
I will notify you when I finish developing.

**Comment by empedia** [comment]
Just wondering if there is any update on when something like this will be implemented yet?

**Comment by CaryTrivett** [comment]
> Just wondering if there is any update on when something like this will be implemented yet?

This is already supported in version 0.10.1 and is accessed at

/private/api/stable/webpages/:id/preview

But there is a problem, it only supports accessing html. If you access MHTML or webarchive , you will get an error.

0.10.2 will support all formats

**Comment by CaryTrivett** [comment]
@empedia  0.10.2 is released.

**Comment by empedia** [comment]
Thanks for this.  It looks like demo.hamsterbase.com is down or unavailable for me. Do you have an alternative demo site or can you bring this one back. 

Many thanks and looking forward to trying this!

**Comment by CaryTrivett** [comment]
> Thanks for this. It looks like demo.hamsterbase.com is down or unavailable for me. Do you have an alternative demo site or can you bring this one back.
> 
> Many thanks and looking forward to trying this!

You can download the hamsterbase desktop and go to Settings / api / Start API Services

Then Entrypoint in your browser
