### ISSUE TITLE
hamsterbase to logseq是不是还不能工作的？

### ISSUE THREAD

**Issue by hellspector** [hamsterbase/hamsterbase#39]
logseq里面是没有sync highlight这个功能的？是不是把obsidian和这个logseq搞混了？

**Comment by CaryTrivett** [comment]
logseq 商店搜索 hamsterbase

**Comment by hellspector** [comment]
就是在logseq商店的hansterbase，但是不能用，不知道在哪里打开那个sync命令，logseq输入命令是用/输入的。ctrl+shift+p，没有这个选项。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: CaryTrivett ***@***.***&gt;
发送时间: 2023年9月9日 20:11
收件人: hamsterbase/hamsterbase ***@***.***&gt;
抄送: hellspector ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [hamsterbase/hamsterbase] hamsterbase to logseq是不是还不能工作的？ (Issue #39)





 
logseq 商店搜索 hamsterbase

**Comment by CaryTrivett** [comment]
<img width="602" alt="image" src="https://github.com/hamsterbase/hamsterbase/assets/9692408/2adcc46a-56a9-4f21-ad87-d01abc527044">


<img width="863" alt="image" src="https://github.com/hamsterbase/hamsterbase/assets/90044465/da1493ea-bd99-47ba-91ee-43ad257ced76">
