### ISSUE TITLE
自带的webdav服务无法使用了

### ISSUE THREAD

**Issue by Travisss** [hamsterbase/hamsterbase#40]
昨天还可以配合singlefile插件直接保存网页到hamsterbase，今天下午突然不好用了，核对过设置是没有问题的。
点击插件后如下图所示，一直卡在这个样子。 
![微信截图_20230914165727](https://github.com/hamsterbase/hamsterbase/assets/20080169/be0d4187-b1eb-419c-b4fc-30a3a3ee77b4)

无奈用apachewebdav项目映射了inbox目录，可正常使用。

**Comment by Travisss** [comment]
一开始我还以为是反代有问题，又尝试了端口转发，一样

**Comment by CaryTrivett** [comment]
singlefile 升级导致的，导致 hamsterbase 不兼容。

**Comment by CaryTrivett** [comment]
我适配一下。

**Comment by acotor** [comment]
SingleFile 1.22.6, Hamsterbase 0.13.1
- 确认过保存位置的URL，以及Hamsterbase Highlighter是可以正常保存的。
- 在 SingleFile 挂起保存项一直在。
- Nginx 站点访问日志可以看到有请求
```
hamster [22/Aug/2024:16:48:01 +0800] "HEAD /external/api/singlefile/Proxmox%20ve%20%E4%B8%ADlxc%E5%AE%B9%E5%99%A8%E5%BC%80%E5%90%AFtun%20-%20%E7%BE%A4%E5%8F%B71978%20-%20%E5%8D%9A%E5%AE%A2%E5%9B%AD%20(2024_8_22%2016_48_00)%20(5).html HTTP/2.0" 200 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36 Edg/127.0.0.0" "-"
```
