### ISSUE TITLE
Windows桌面端是否具有导出功能？

### ISSUE THREAD

**Issue by benjaminyzhang** [hamsterbase/hamsterbase#41]
作者好！

我是用Singlefile导入网页到Inbox，标注后想要将原网页导出为Singlefile那种Html文件，请问目前是否有实现？我还未找到该功能。

**Comment by CaryTrivett** [comment]
不好意思，暂时没有开发。 目前只能通过自带的 API ，自己实现这个功能。

**Comment by CaryTrivett** [comment]
0.10.0 支持
