### ISSUE TITLE
[BUG] 使用 Docker部署 + Nignx反代 后 webdav API 似乎没法接收文件

### ISSUE THREAD

**Issue by lurenJBD** [hamsterbase/hamsterbase#42]
### 具体表现为SingleFile一直卡在 “保存进度100%”，而HTML文件没法上传到Nignx端
![image](https://github.com/hamsterbase/hamsterbase/assets/31967654/c8e2e89d-fd7a-4d56-8fc6-dfb44fc5ac02)

### singlefile配置
![image](https://github.com/hamsterbase/hamsterbase/assets/31967654/aa6e65f6-8351-4252-a9ab-0cd17a0a9009)

### 使用宝塔查看Nignx日志，显示确认文件没有上传到，但HTTP状态又是显示200
![image](https://github.com/hamsterbase/hamsterbase/assets/31967654/06432dcb-2965-4fd8-9c97-2ec947ecf2ce)

### Nignx反代配置，确认有加WS反代
![image](https://github.com/hamsterbase/hamsterbase/assets/31967654/a6fba27f-f128-4788-a785-a4cd0e319276)

![image](https://github.com/hamsterbase/hamsterbase/assets/31967654/429e4729-e8e3-48d8-855a-d4f258d8a0b7)

目前hamsterbase网页是能正常地访问，手动在上传页面上传HTML文件也可以正常添加

**如果把 singlefile 的 webdav 地址 改为 http: //192.168.1.10:3001/external/api/singlefile，即内网不用nignx反代的地址，是完全正常的，所以判断为Nignx反代中应该有某些问题，或者是singlefile的问题。**

已经查看了 #40 的 issues，确认版本为 0.9.2 ，SingleFile 版本为 1.22.7（使用Chrome商店安装，浏览器Chrome 103/Edge 114）

查看 #22 的 issues，我这边网页在Nignx反代下是可以正常访问的，使用devtools查看也没报错
![image](https://github.com/hamsterbase/hamsterbase/assets/31967654/bd28d47a-9575-4664-991f-a08053bace8c)

**Comment by lurenJBD** [comment]
补充说明一下，不管是 CF的安全日志 还是 我服务器本身的WAF 都没有拦截记录，所以我可以断定是 HTML文件 不知道为何没法上传

**Comment by CaryTrivett** [comment]
@HEAD('/singlefile/:filename')
  head(ctx: RouteContent<{ filename: string }, string>) {
    throw new NotFoundError('not found');
  }

麻烦让 head 接口返回 404.

hamsterbase 没有真正实现 webdav ， 而是通过参看 singlefile 的源码，模拟实现了一个 put 接口。

如果 head 文件返回 200 ，singlefile 会认为文件已保存了。  只有返回 404 才会继续调用 put 接口保存

**Comment by lurenJBD** [comment]
![Snipaste_2023-10-27_18-40-00](https://github.com/hamsterbase/hamsterbase/assets/31967654/a4f2314a-f1e0-44a7-9322-1196010121e2)

非常感谢回复，我已经将head请求的返回改为404了，接着PUT的请求显示为200，但实际上HTML文件依旧是没被上传，防火墙和WAF均未有拦截记录，感觉还是Nignx反代的问题。
