### ISSUE TITLE
删除功能异常

### ISSUE THREAD

**Issue by hihi427** [hamsterbase/hamsterbase#43]
windows版 删除网页后  只是删除了显示,   知识库文件夹内的内容 没有被删除   时间长了会积累很大吧
文件名不是明文所以也没法手动删除,   希望增加清理缓存按钮 或者点击删除后把文件清理到

**Comment by CaryTrivett** [comment]
目前是这么设计的，未来会支持清理缓存

**Comment by hihi427** [comment]
> 目前是这么设计的，未来会支持清理缓存

打算就等这个功能有了 开始正式用   出了麻烦大佬踹我一脚

**Comment by CaryTrivett** [comment]
> > 目前是这么设计的，未来会支持清理缓存
> 
> 打算就等这个功能有了 开始正式用 出了麻烦大佬踹我一脚

你可以先用着，未来会有自动清理缓存。

**Comment by CaryTrivett** [comment]
新版本已支持
