### ISSUE TITLE
导入到Hamsterbase的html原文件怎么搜不到了

### ISSUE THREAD

**Issue by grayguest** [hamsterbase/hamsterbase#47]
怎么恢复所有格式为html的原文件呢？

**Comment by CaryTrivett** [comment]
hamsterbase 会把原文件压缩，可以在软件里导出。

<img width="320" alt="CleanShot 2024-03-19 at 20 49 50@2x" src="https://github.com/hamsterbase/hamsterbase/assets/90044465/fd52e78c-b956-455c-bea6-c2744459f5d1">
