### ISSUE TITLE
docker版本希望可以添加一个全屏查看或是查看原始html功能

### ISSUE THREAD

**Issue by zyqkdl** [hamsterbase/hamsterbase#49]
部分网页类似csdn，拉取下来的html有侧边栏广告，直接用浏览器打开本地的html文件因为是全屏的，所以侧边栏位置是正确的。但是在docker版里查看，因为多了左右的列表，网页变窄了，广告会遮挡网页主要内容。
因此希望添加一个全屏查看功能，或是新选项卡打开原始html的功能。最好是前者，这样能支持批注，谢谢！

**Comment by CaryTrivett** [comment]
<img width="420" alt="image" src="https://github.com/hamsterbase/hamsterbase/assets/90044465/c7c4e214-ae94-4d05-b38d-f1805be0b7aa">


已经支持了，只需要切换到列表模式，然后双击即可。

**Comment by CaryTrivett** [comment]
<img width="722" alt="image" src="https://github.com/hamsterbase/hamsterbase/assets/90044465/e035d2cc-0c48-486e-b005-de06f1daf21b">

如果是 11.0 ，还可以完全收起来。
