### ISSUE TITLE
Feature voting  功能投票

### ISSUE THREAD

**Issue by CaryTrivett** [hamsterbase/hamsterbase#5]
What features do you want hamsterbase to support?
The order of development is independent of the number of votes.
You can also leave a message.

你希望 hamsterbase 支持什么功能？
开发顺序和投票数无关。
也可以留言。

**Comment by CaryTrivett** [comment]
支持 Webdav 同步

**Comment by CaryTrivett** [comment]
Annotate directly in the browser
在浏览器里直接批注

**Comment by CaryTrivett** [comment]
Reading mode.

阅读模式。

**Comment by CaryTrivett** [comment]
Support for epub 
支持 epub 电子书

**Comment by CaryTrivett** [comment]
Desktop client
桌面客户端

**Comment by CaryTrivett** [comment]
iOS and Android clients
iOS 和 安卓客户端

**Comment by CaryTrivett** [comment]
A separate annotation page that displays all annotations.
独立的批注页面，显示所有批注。

**Comment by CaryTrivett** [comment]
Custom themes
自定义主题

**Comment by CaryTrivett** [comment]
Languages other than Chinese and English
除了中文与英文以外的语言

**Comment by CaryTrivett** [comment]
Compatible with RSS APIs such as GoogleReader and Fever 
兼容 rss API , 如 googlereader ,fever

**Comment by CaryTrivett** [comment]
Import data from a mailbox
从邮箱导入数据

**Comment by CaryTrivett** [comment]
Export highlights
导出高亮

**Comment by CaryTrivett** [comment]
command palette

命令面板


<img width="726" alt="image" src="https://user-images.githubusercontent.com/90044465/201668238-30b0c7ab-5299-4baf-a43e-2f0f24096ede.png">

**Comment by CaryTrivett** [comment]
TOC

网页目录

**Comment by CaryTrivett** [comment]
bi-directional link
双向链接

**Comment by CaryTrivett** [comment]
Statistics page
统计页面

**Comment by CaryTrivett** [comment]
Index external data
索引外部数据

**Comment by CaryTrivett** [comment]
TTS
TTS 朗读

**Comment by CaryTrivett** [comment]
Export web page
导出网页

**Comment by CaryTrivett** [comment]
Extension 插件系统

**Comment by Ch4mpa9ne** [comment]
支持渲染与索引md，支持索引任意文本文件，包括*.txt *.cpp *.py *.php等

**Comment by susc** [comment]
用户系统：目前无需任何认证即可访问、修改、删除系统中的数据，存在数据安全隐患

**Comment by CaryTrivett** [comment]
> 用户系统：目前无需任何认证即可访问、修改、删除系统中的数据，存在数据安全隐患

启动时加上 --password 参数即可设置密码。

**Comment by FirstKaiXin** [comment]
将文件移动到 workspace/inbox 中只上传 hamsterbase 中不存在的文件，存在的文件则不上传

**Comment by CaryTrivett** [comment]
> 将文件移动到 workspace/inbox 中只上传 hamsterbase 中不存在的文件，存在的文件则不上传

如果是相同文件，应该是会自动去重的。
