### ISSUE TITLE
HamsterBase 反馈

### ISSUE THREAD

**Issue by SNANA51832** [hamsterbase/hamsterbase#58]
1. 最左侧能否做出分别隐藏两栏的功能
2. 默认的滚动条太丑了，可以参考下同类软件设计
3. 插件的初始阅读界面不好看，也不能调整字体字号间距等等
4. 不能根据屏幕缩放调整网页大小
5. 很多网页不支持
6. 即使支持的网页会有和原本网页不同的情况
7. 插件必须在有软件启动的情况下才能标记，但是软件没有后台运行放托盘、开机自启、静默启动等功能
![PixPin_2024-10-23_08-58-21](https://github.com/user-attachments/assets/bad05e15-27da-4945-a9aa-b1b4ad1a2a91)
![PixPin_2024-10-23_09-16-56](https://github.com/user-attachments/assets/24df8343-d6b9-4c6d-b961-eaba7d41eb4d)

**Comment by CaryTrivett** [comment]
1. 最左侧能否做出分别隐藏两栏的功能

这个支持的。 最左边的可以拖动隐藏， 中间的切换列表模式就行了

2. 默认的滚动条太丑了，可以参考下同类软件设计

这个应该是改漏了， windows 默认的比较丑

3. 插件的初始阅读界面不好看，也不能调整字体字号间距等等
之后会做

4. 不能根据屏幕缩放调整网页大小

没懂

5. 很多网页不支持

请提交 PR 举例子，把文件传上来

6. 即使支持的网页会有和原本网页不同的情况

同上

7. 插件必须在有软件启动的情况下才能标记，但是软件没有后台运行放托盘、开机自启、静默启动等功能

这个会做

**Comment by CaryTrivett** [comment]
这个 issue 提交了太多东西，我先关了。 麻烦拆一下
